### ISSUE TITLE
Could not trigger aind-data-transfer-service

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/aind-watchdog-service#20]
I'm trying to deploy the watchdog service on dynamic foraging rigs (see [this issue](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/477) where I document every step). I did some tests on my local PC. The watchdog can now monitor the folder and upload data to VAST, but cannot trigger the aind-data-transfer-service. [This line](https://github.com/AllenNeuralDynamics/aind-watchdog-service/blob/5b9cd7a9edadfcb3571ffcb6cc919671d025273f/src/aind_watchdog_service/run_job.py#L206) returns `status_code = 406` with a bunch of validation errors:

```
  Error parsing {"user_email":null,"email_notification_types":null,"project_name":"Behavior Platform","process_capsule_id":null,"s3_bucket":"private","platform":{"name":"Behavior platform","abbreviation":"behavior"},"modalities":[{"modality":{"name":"Behavior","abbreviation":"behavior"},"source":"\\\\allen\\aind\\scratch\\dynamic_foraging_rig_transfer/behavior_727353_2024-06-03_09-01-34/behavior","compress_raw_data":false,"extra_configs":null,"slurm_settings":null,"output_folder_name":"behavior"},{"modality":{"name":"Behavior videos","abbreviation":"behavior-videos"},"source":"\\\\allen\\aind\\scratch\\dynamic_foraging_rig_transfer/behavior_727353_2024-06-03_09-01-34/behavior-videos","compress_raw_data":false,"extra_configs":null,"slurm_settings":null,"output_folder_name":"behavior-videos"},{"modality":{"name":"Fiber photometry","abbreviation":"fib"},"source":"\\\\allen\\aind\\scratch\\dynamic_foraging_rig_transfer/behavior_727353_2024-06-03_09-01-34/fib","compress_raw_data":false,"extra_configs":null,"slurm_settings":null,"output_folder_name":"fib"}],"subject_id":"727353","acq_datetime":"2024-02-12T09:14:43","metadata_dir":"\\\\allen\\aind\\scratch\\dynamic_foraging_rig_transfer/behavior_727353_2024-06-03_09-01-34","metadata_dir_force":false,"force_cloud_sync":false,"s3_prefix":"behavior_727353_2024-02-12_09-14-43"}: 6 validation errors for BasicUploadJobConfigs
  modalities.0.slurm_settings
    Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
  modalities.0.output_folder_name
    Extra inputs are not permitted [type=extra_forbidden, input_value='behavior', input_type=str]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
  modalities.1.slurm_settings
    Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
  modalities.1.output_folder_name
    Extra inputs are not permitted [type=extra_forbidden, input_value='behavior-videos', input_type=str]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
  modalities.2.slurm_settings
    Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
  modalities.2.output_folder_name
    Extra inputs are not permitted [type=extra_forbidden, input_value='fib', input_type=str]
      For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
``` 

It seems like incompatible schemas? Here are my installed packages:
```
aind-data-schema-models       0.1.1
aind-data-transfer-models     0.4.0
aind-slurm-rest               0.1.0
aind-watchdog-service         0.0.0  
```

Here is my `manifest.yml` file, just in case I missed something

```yml
acquisition_datetime: 2024-02-12 09:14:43+00:00
capsule_id: null
destination: \\allen\aind\scratch\dynamic_foraging_rig_transfer
processor_full_name: Han Hou
modalities:
  behavior:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-03_09-01-34\behavior
  behavior-videos:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-03_09-01-34\behavior-videos
  fib:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-03_09-01-34\fib
schemas:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-03_09-01-34\metadata-dir\session.json
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-03_09-01-34\metadata-dir\rig_447-1-A_2024-05-29_09_31_02.json
name: behavior_727353_2024-06-03_09-01-34
platform: behavior
s3_bucket: s3://aind-behavior-data/foraging_watchdog_upload
subject_id: 727353
schedule_time: null
project_name: Behavior Platform
script: {}
``` 

@arielleleon any ideas?
