### ISSUE TITLE
Better handle slashes in manifest.yml

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/aind-watchdog-service#26]
**Is your feature request related to a problem? Please describe.**
In this [issue](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/issues/477#issuecomment-2187563346), aind-data-transfer-service failed, likely due to a mixture of forward and backward slashes in the submitted job. Using all forward slashes (/) seems to solve the problem.

Sample yml file that failed:
```yml
acquisition_datetime: 2024-06-03 09:01:34+00:00
name: behavior_727353_2024-06-05_08-33-51
platform: behavior
subject_id: 724555
capsule_id: null
mount: null
destination: \\allen\aind\scratch\dynamic_foraging_rig_transfer
s3_bucket: private
processor_full_name: Han Hou
modalities:
  behavior:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-05_08-33-51\behavior
  behavior-videos:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-05_08-33-51\behavior-videos
  fib:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-05_08-33-51\fib
schemas:
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-05_08-33-51\metadata-dir\session.json
  - C:\Users\admin\Documents\aind_watchdog_test\test_behavior_file\behavior_727353_2024-06-05_08-33-51\metadata-dir\rig_447-1-A_2024-05-29_09_31_02.json
schedule_time: null
project_name: Behavior Platform
script: {}
```

Sample yml file that worked:

```yml
acquisition_datetime: 2024-06-03 09:01:34+00:00
name: behavior_724555_2024-06-21_13-54-00
platform: behavior
subject_id: 724555
capsule_id: null
mount: null
destination: //allen/aind/scratch/dynamic_foraging_rig_transfer
s3_bucket: private
processor_full_name: Han Hou
modalities:
  behavior:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/behavior
  behavior-videos:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/behavior-videos
  fib:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/fib
schemas:
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/metadata-dir/session.json
  - C:/Users/admin/Documents/aind_watchdog_test/test_behavior_file/behavior_724555_2024-06-21_13-54-00/metadata-dir/rig_447-1-B_2024-05-29_11_09_25.json
schedule_time: null
project_name: Behavior Platform
script: {}
```

**Describe the solution you'd like**
The WatchDog gracefully handle the slashes in the manifest.yml file.

**Describe alternatives you've considered**
An alternative would be to document this requirement and highlight it in the example yml files.

**Additional context**
None.
